### ISSUE TITLE
Error when I try to go to "all courses"

### ISSUE THREAD

**Issue by kalenhussey** [FMCorz/moodle-block_stash#19]
Hi, I am trying to set up Stash on my Moodle site. I have multiple courses and initially didn't understand how stash works, so I tried to put a block on the "courses" section instead of inside a course. I got this error:
 The stash is not enabled. Was the block added to the course? 

And I backed out and added the block to the course, which worked fine. But now every time I try to click on "all courses" it shows me a page with this error instead of taking me to all courses. 

Do I need to delete something for this to stop happening?
![stash not enabled error](https://user-images.githubusercontent.com/42651222/44685697-51498380-aa09-11e8-8c1e-6fce8a4e2497.jpg)

**Comment by FMCorz** [comment]
Thanks for the report.

The bug is now fixed, it will be released in the next version of Stash, meanwhile you can download the zip of the `master` branch.

It turns out that adding the block in the courses list should not be possible, and lead to this unexpected error. We've added a fix to the plugin to ensure that this error does not prevent the page from loading anymore, this should enable you to remove the block.

At a later stage, we should prevent Moodle from offering the block as an option an non-course pages.
